
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";

interface ApplyDisclaimerModalProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    onConfirm: (disclaimerText: string) => void;
}

const DISCLAIMER_POINTS = [
    "Snapshot of Posting Only: This record is a static summary of the original opportunity listing generated by the NxteVia platform for record-keeping purposes only. NxteVia does not verify if these terms were final. The actual terms of engagement (including final pay, start dates, and deliverables) may differ and must be memorialized in a separate written agreement between the parties.",
    "Not an Employment Contract: This record does not constitute an offer of employment, an employment contract, or an independent contractor agreement between NxteVia and any user.",
    "No Agency Relationship: NxteVia Inc. acts solely as a technology facilitator. NxteVia Inc. is not a temporary help agency, a recruiter, or a joint employer of any individual named in this record.",
    "User Responsibility: The parties listed above are solely responsible for executing their own written agreements to ensure compliance with applicable labour, tax, and intellectual property laws."
];

export function ApplyDisclaimerModal({ open, onOpenChange, onConfirm }: ApplyDisclaimerModalProps) {
    const handleConfirm = () => {
        // We can concatenate the text to verify what was acknowledged if needed
        const fullText = `LEGAL DISCLAIMER ACKNOWLEDGED:\n\n` + DISCLAIMER_POINTS.map((p, i) => `${i + 1}. ${p}`).join("\n\n");
        onConfirm(fullText);
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-[600px] max-h-[85vh] flex flex-col p-0 gap-0 overflow-hidden text-slate-900 dark:text-slate-100 bg-white dark:bg-slate-950 border-slate-200 dark:border-slate-800">
                <DialogHeader className="p-6 pb-2 space-y-2">
                    <DialogTitle className="text-xl font-bold text-red-600 dark:text-red-500 flex items-center gap-2">
                        LEGAL DISCLAIMER: RECORD OF POSTING ONLY
                    </DialogTitle>
                    <DialogDescription className="text-base text-slate-600 dark:text-slate-400">
                        Please review and acknowledge the following terms before applying:
                    </DialogDescription>
                </DialogHeader>

                <ScrollArea className="flex-1 p-6 pt-2">
                    <div className="space-y-4 text-sm text-slate-700 dark:text-slate-300">
                        {DISCLAIMER_POINTS.map((point, index) => (
                            <div key={index} className="flex gap-3 bg-slate-50 dark:bg-slate-900/50 p-3 rounded-lg border border-slate-100 dark:border-slate-800">
                                <span className="flex-none font-bold text-slate-900 dark:text-slate-100 bg-slate-200 dark:bg-slate-800 w-6 h-6 rounded-full flex items-center justify-center text-xs">
                                    {index + 1}
                                </span>
                                <p className="leading-relaxed">{point}</p>
                            </div>
                        ))}
                    </div>
                </ScrollArea>

                <DialogFooter className="p-6 pt-4 border-t border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/50 flex flex-col sm:flex-row gap-2">
                    <Button
                        variant="outline"
                        onClick={() => onOpenChange(false)}
                        className="sm:flex-1 text-slate-600 dark:text-slate-300 border-slate-300 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800"
                    >
                        Cancel
                    </Button>
                    <Button
                        onClick={handleConfirm}
                        className="sm:flex-1 bg-red-600 hover:bg-red-700 text-white shadow-md shadow-red-600/20 font-semibold"
                    >
                        I Acknowledge & Apply
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
