import * as React from "react";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { AlertTriangle, FileText } from "lucide-react";

interface HireDisclaimerModalProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    onConfirm: (disclaimerText: string) => void;
}

const DISCLAIMER_POINTS = [
    "Snapshot of Posting Only: This record is a static summary of the original opportunity listing generated by the NxteVia platform for record-keeping purposes only. NxteVia does not verify if these terms were final. The actual terms of engagement (including final pay, start dates, and deliverables) may differ and must be memorialized in a separate written agreement between the parties.",
    "Not an Employment Contract: This record does not constitute an offer of employment, an employment contract, or an independent contractor agreement between NxteVia and any user.",
    "No Agency Relationship: NxteVia Inc. acts solely as a technology facilitator. NxteVia Inc. is not a temporary help agency, a recruiter, or a joint employer of any individual named in this record.",
    "User Responsibility: The parties listed above are solely responsible for executing their own written agreements to ensure compliance with applicable labour, tax, and intellectual property laws."
];

export function HireDisclaimerModal({ open, onOpenChange, onConfirm }: HireDisclaimerModalProps) {
    const handleConfirm = () => {
        const fullText = `LEGAL DISCLAIMER ACKNOWLEDGED:\n\n` + DISCLAIMER_POINTS.map((p, i) => `${i + 1}. ${p}`).join("\n\n");
        onConfirm(fullText);
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2 text-slate-900 dark:text-white uppercase tracking-tight">
                        <FileText className="h-5 w-5 text-primary" />
                        LEGAL DISCLAIMER: RECORD OF SELECTION ONLY
                    </DialogTitle>
                    <DialogDescription>
                        Please review and acknowledge the following legal terms before proceeding.
                    </DialogDescription>
                </DialogHeader>

                <div className="space-y-4 py-2 text-sm text-slate-700 dark:text-slate-300">
                    {DISCLAIMER_POINTS.map((point, idx) => {
                        const [title, ...rest] = point.split(":");
                        return (
                            <div key={idx} className="bg-slate-50 dark:bg-slate-900/50 p-3 rounded-lg border border-slate-100 dark:border-slate-800">
                                <p>
                                    <span className="font-bold text-slate-900 dark:text-white">{idx + 1}. {title}:</span>
                                    {rest.join(":")}
                                </p>
                            </div>
                        );
                    })}
                </div>

                <DialogFooter className="gap-2 sm:gap-0 pt-2">
                    <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
                    <Button onClick={handleConfirm} className="bg-primary hover:bg-primary/90">
                        I Acknowledge & Select
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
